### ISSUE TITLE
Unprivileged installation package/instructions

### ISSUE THREAD

**Issue by p-mongo** [mongodb/mut#13]
Please publish mut to pypi or provide instructions for installing it in an unprivileged environment.

<pre>
tk% bash -c "$(curl -fsSL https://raw.githubusercontent.com/mongodb/mut/master/install.sh)"
Install dependencies:  sudo apt-get update
OK? n

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for mpush: 
Sorry, try again.
[sudo] password for mpush: 
Sorry, try again.
[sudo] password for mpush: 
sudo: 3 incorrect password attempts
</pre>

Even though I declined to have mut installer make changes to my system, it attempted to do so anyway and failed.

**Comment by i80and** [comment]
`python3 -m pip install mut` will now install mut!

**Comment by p-mongo** [comment]
Thank you.
